<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>hiconic.platform.reflex</groupId>
		<artifactId>parent</artifactId>
		<version>[1.0,1.1)</version>
	</parent>
	<artifactId>external-tools-rx-module</artifactId>
	<version>1.0.2</version>
	<dependencies>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>reflex-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>external-tools-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>external-tools-configuration-model</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>com.braintribe.systemtools</groupId>
			<artifactId>system-tools</artifactId>
			<version>${V.com.braintribe.systemtools}</version>
		</dependency>
	</dependencies>
</project>
