<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>hiconic.platform.reflex</groupId>
		<artifactId>parent</artifactId>
		<version>[1.0,1.1)</version>
	</parent>
	<artifactId>configuration-assembly-processing</artifactId>
	<version>1.0.3</version>
	<dependencies>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>reflex-platform</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>com.braintribe.gm</groupId>
			<artifactId>configuration-assembly-model</artifactId>
			<version>${V.com.braintribe.gm}</version>
			<?tag asset?>
		</dependency>
	</dependencies>
</project>
