accesses:
  - !hiconic.rx.access.hibernate.model.configuration.HibernateAccess
    accessId: main-access
    #dataModelName: rx-test:configured-main-access-model
    dataModelName: hiconic.platform.reflex:hibernate-test-model
    databaseName: main-db