<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>hiconic.platform.reflex</groupId>
		<artifactId>parent</artifactId>
		<version>[1.0,1.1)</version>
	</parent>
	<artifactId>browser-acceptance-web-rx-module</artifactId>
	<version>1.0.1</version>
	<dependencies>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>reflex-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>web-server-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>web-security-rx-module</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>web-rpc-server-rx-module</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>browser-acceptance-configuration-model</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>browser-acceptance-rx-module</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>browser-acceptance-webapp</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
			<type>pom</type>
		</dependency>
	</dependencies>
</project>
